spring.application.name=dacn
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.servlet.context-path=/api/v1
server.port=${PORT:8080}
# JWT
jwt.secret-key=843567893696976453275974432697R634976R738467TR678T34865R6834R8763T478378637664538745673865783678548735687R3
jwt.access-expiration=604800000
jwt.refresh-expiration=604800000

# Swagger
springdoc.swagger-ui.path=/swagger-ui/index.html

# Cloudinary
cloudinary.cloud_name=ddeucv71n
cloudinary.api_key=143313557212593
cloudinary.api_secret=mq2TXZwBgvGBjl1rcr45r23R8b0
cloudinary.folder=dacn
